### ISSUE TITLE
Discrepancy between code and plot results

### ISSUE THREAD

**Issue by andreihushcha** [learn-co-curriculum/dsc-standard-normal-distribution#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6852/pages/the-standard-normal-distribution?module_item_id=608889
https://github.com/learn-co-curriculum/dsc-standard-normal-distribution

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

``` 
Code is wrong.  Should be sns.distplot(), instead of sns.displot(). 
The plot below a code is a .png picture, not a real seaborn plot.
```

### Concern

![Screenshot 2023-10-14 170129](https://github.com/learn-co-curriculum/dsc-standard-normal-distribution/assets/117996551/d9ec1cc4-73ea-44d4-be66-2a5f67a7f985)

![Screenshot 2023-10-14 170001](https://github.com/learn-co-curriculum/dsc-standard-normal-distribution/assets/117996551/96fac05a-3a02-4819-af58-a842ee79c83d)

## (Optional) Proposed Solution

import numpy as np
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

mean1, sd1 = 5, 3 # dist 1 
mean2, sd2 = 10, 2 # dist 2 
d1 = np.random.normal(mean1, sd1, 1000)
d2 = np.random.normal(mean2, sd2, 1000)
sns.distplot(d1);
sns.distplot(d2);

sns.distplot([(x - d1.mean())/d1.std() for x in d1]);
sns.distplot([(x - d2.mean())/d2.std() for x in d2]);

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you pointing this out. I have changed from `distplot` to `displot`.
